# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://University-of-Bojnurd.github.io/test-nbdev/"

git_url = "https://github.com/University-of-Bojnurd/test-nbdev/tree/master/"

def custom_doc_links(name): return None
